[[edge_functions]]
  path = "/api/claude"
  function = "claude-proxy"

[[edge_functions]]
  path = "/api/img"
  function = "img-proxy"

[[edge_functions]]
  path = "/api/catimg"
  function = "img-cat-proxy"

# deploy trigger v2
